### ISSUE TITLE
Naming and duplication of class selectors (css styles)

### ISSUE THREAD

**Issue by taras-pyzo** [keenethics/banker-adviser-lending-email#6]
Since the project does not contain additional tools like `webpack` or styles aren't written using `BEM` or `CSS Modules` approaches use one principle everywhere in class selectors to prevent duplication.

For example, please be more specific and use prefix about- everywhere for page About and so on.
https://github.com/keenethics/banker-adviser-lending-email/blob/63bc334184bacfdee712a26052df776bc537ce59/src/client/components/about/about.css#L68

**Comment by stefan9541** [comment]
the project compiled by create-react-app wich use webpack inside it
